export default {
    resources: {
        copyright: "© 2020 All rights reserved",
        team: "WeCan Team", 
        actions: "Actions",
        grivna: "UAH",
        dollar: "USD",
        euro: "EUR",
        rubl: "RUB",
        versts: "Versts",
        meters: "Meters",
        yards: "Yards",
        foots: "Foots",
        miles: "Miles",
        convert: "Convert",
        calculator: "Calc",
        converter: "Converter",
        paint: "Paint",
        table: "Table",
        login: "Login",
        email: "Email",
        phone: "Phone",
        changeModeApp: "My account",
        changeModeAccount: "Back to App",
        logout: "Log out",
        number: "Number",
        firstName: "First name",
        lastName: "Last name",
        age: "Age",
        lengths: "Lengths",
        currencies: "Currencies",
        city: "City",
        enterFirstName: "Enter first name",
        enterLastName: "Enter last name",
        enterAge: "Enter age",
        enterCity: "Enter city",
        createStudent: "Create student",
        clearGroup: "Clear group",
        deleteGroup: "Delete group",
        btnUpdate: "Update",
        btnDelete: "Delete",
        btnOk: "Ok",
        btnCancel: "Cancel",
        settings: "Settings",
        labelLanguage: "Choose language",
        back: "Back",
        incorrectLogin: "Incorrect login",
        incorrectMail: "Incorrect mail",
        incorrectPhone: "Incorrect phone",
        incorrectFirstName: "Incorrect first name",
        incorrectLastName: "Incorrect last name",
        incorrectAge: "Incorrect age",
        incorrectCity: "Incorrect city",
        successCreateStudent: "Student was created",
        successCreateGroup: "New group was created",
        successUpdateStudent: "Student was updated",
        successDeleteStudent: "Student was deleted",
        successClearGroup: "Group was cleared",
        successDeleteGroup: "Group was deleted",
        sucessRenameGroup: "Group was renamed",
        failRenameGroup: "Incorrect group name",
        confirm: "Confirm action",
        confirmClearGroup: "Clear group?",
        confirmDeleteGroup: "Delete group?",
        resetAll: "Reset all",
        confirmReset: "Reset all?",
        successResetAll: "Application was reset",
        en: "English",
        ru: "Русский",
        ar: "Arab",
        online: "Online",
        chats: "Chats",
        send: "Send",
        leave: "Leave chat",
        login: "Login",
        activeSessions: "Active sessions",
        popularMode: "Popular mode",
        CRUD: "CRUD",
        useChat: "Use chat",
        device: "Device",
        geo: "Geo",
        publicIP: "Public IP",
        browser: "Browser",
        color: "Color",
        background: "Background",
        size: "Size",
        clear: "Clear",
        value: "Value",
        result: "Result",
        incorrectValue: "Incorrect value",
        change: "Change",
        save: "Save",
        additionalInfo: "Additional information"
    },
    dialogs: {
        startFromAddingGroup: "Start from adding group",
        enterYourMessageHere: "Enter your message here",
    },
}