export default {
    resources: {
        copyright: "© 2020 Все права защищены",
        team: "WeCan Team", 
        actions: "Действия",
        grivna: "UAH",
        dollar: "USD",
        euro: "EUR",
        rubl: "RUB",
        versts: "Вёрсты",
        meters: "Метры",
        yards: "Ярды",
        foots: "Футы",
        miles: "Мили",
        convert: "Конвертировать",
        calculator: "Калькулятор",
        converter: "Конвертер",
        paint: "Рисовалка",
        table: "Таблица",
        login: "Логин",
        email: "Электронная почта",
        phone: "Телефон",
        changeModeApp: "Mой аккаунт",
        changeModeAccount: "Вернуться",
        logout: "Выйти",
        number: "Номер",
        firstName: "Имя",
        lastName: "Фамилия",
        age: "Возраст",
        city: "Город",
        lengths: "Величины",
        currencies: "Валюты",
        enterFirstName: "Введите имя",
        enterLastName: "Введите фамилию",
        enterAge: "Введите возраст",
        enterCity: "Введите город",
        createStudent: "Создать студента",
        clearGroup: "Очистить группу",
        deleteGroup: "Удалить группу",
        btnUpdate: "Обновить",
        btnDelete: "Удалить",
        btnOk: "Ок",
        btnCancel: "Отмена",
        settings: "Настройки",
        labelLanguage: "Выберите язык",
        back: "Вернуться",
        incorrectLogin: "Неверный логин",
        incorrectMail: "Неверная электронная почта",
        incorrectPhone: "Неверный телефон",
        incorrectFirstName: "Некорректное имя",
        incorrectLastName: "Некорректная фамилия",
        incorrectAge: "Некорректный возраст",
        incorrectCity: "Некорректный город",
        successCreateStudent: "Студент успешно создан",
        successCreateGroup: "Новая группа успешно создана",
        successUpdateStudent: "Студент успешно обновлен",
        successDeleteStudent: "Студент успешно удален",
        successClearGroup: "Группа была успешно очищена",
        successDeleteGroup: "Группа была успешно удалена",
        sucessRenameGroup: "Группа успешно переименована",
        failRenameGroup: "Некорректное имя группы",
        confirm: "Подтвердите действие",
        confirmClearGroup: "Очистить группу?",
        confirmDeleteGroup: "Удалить группу?",
        resetAll: "Сбросить все",
        confirmReset: "Сбросить все?",
        successResetAll: "Приложение было обнулено",
        en: "English",
        ru: "Русский",
        ar: "Arab",
        online: "В сети",
        chats: "Диалоги",
        send: "Отправить",
        leave: "Покинуть чат",
        login: "Логин",
        activeSessions: "Активные сессии",
        popularMode: "Популярный мод",
        CRUD: "CRUD",
        useChat: "Использование чата",
        device: "Устройство",
        geo: "Гео",
        publicIP: "Публичный IP",
        browser: "Браузер",
        color: "Цвет",
        background: "Фон",
        size: "Размер",
        clear: "Очистить",
        value: "Значение",
        result: "Результат",
        incorrectValue: "Некорректное значение",
        change: "Изменить",
        save: "Сохранить",
        additionalInfo: "Дополнительная информация"
    },
    dialogs: {
        startFromAddingGroup: "Начни с создания группы",
        enterYourMessageHere: "Введите ваше сообщения здесь",
    }
}