module.exports = {
    port: 3000,
    connectionString: 'postgressql://postgres:Qazwsx123@localhost:5432/userdb',
    mongoDataBaseName: 'users',
    mongoCollectionName: 'users',
    url:{
        root: "/",
        checkTeacher: "/check",
        insertTeacher: "/insert_teacher",
        getGroups: "/get-groups",
        getStudents: "/get-students",
        renameGroup: "/rename-group",
        createGroup: "/create-group",
        updateTeacher: "/update_teacher",
        createStudent: "/create-student",
        clearGroup: "/clear-group",
        deleteGroup: "/delete-group",
        updateStudent: "/update-student",
        deleteStudent: "/delete-student",
        resetStudents: "/reset-students",
        resetGroups: "/reset-groups",
        sendTime: "/send-time",
        getAdminData: "/get-admin-data",
    },
}